name: cpi-count--test-ec2
on: workflow_dispatch

permissions:
  id-token: write

jobs:
  setup-runner:
    name: Start EC2 runner
    runs-on: ubuntu-latest
    outputs:
      runner-label: ${{ steps.start-runner.outputs.runner-label }}
      ec2-instance-id: ${{ steps.start-runner.outputs.ec2-instance-id }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Start AWS Runner
        id: start-runner
        uses: ./.github/actions/aws-runner
        with:
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          subnet-id: ${{ secrets.AWS_SUBNET_ID }}
          security-group-id: ${{ secrets.AWS_SECURITY_GROUP_ID }}
          # See this Intel VTune documentation that lists the instances that support
          # hardware events:
          # https://www.intel.com/content/www/us/en/developer/articles/technical/intel-vtune-amplifier-functionality-on-aws-instances.html
          instance-type: 'c5.9xlarge'
          aws-image-id: 'ami-0884d2865dbe9de4b'  # Ubuntu 22.04 LTS in us-east-2
          pre-runner-script: |
            sudo apt update -y && \
            sudo apt install docker git libicu -y
            sudo systemctl enable docker

  # We set `perf_event_paranoid=0` so that we can run the cpi-count program and
  # tests without elevated privileges.
  ensure-perf-event-paranoid:
    name: Ensure `perf_event_paranoid` is set
    needs: setup-runner
    runs-on: ${{ needs.setup-runner.outputs.runner-label }}
    steps:
      - name: Check current value
        run: cat /proc/sys/kernel/perf_event_paranoid
      - name: Ensure value is 0
        run: echo 0 | sudo tee /proc/sys/kernel/perf_event_paranoid 1>/dev/null
      - name: Check updated value
        run: cat /proc/sys/kernel/perf_event_paranoid

  print-available-events:
    name: Print available events that can be used with `perf -e`
    needs: [setup-runner, ensure-perf-event-paranoid]
    runs-on: ${{ needs.setup-runner.outputs.runner-label }}
    steps:
      - name: Print available events
        run: perf list

  run-tests:
    name: Run tests
    needs: [setup-runner, ensure-perf-event-paranoid, print-available-events]
    runs-on: ${{ needs.setup-runner.outputs.runner-label }}
    permissions:
      contents: read
    steps:
      # It seems that when using a self-hosted runner with an Ubuntu image,
      # the $HOME directory is not created/maintained. We manually create it
      # here because the `go` installation requires a valid $HOME directory
      # for several `go` environment variables.
      - name: Create home directory
        run: |
          mkdir -p /home/runner
          echo "HOME=/home/runner" >> $GITHUB_ENV
      - name: Print environment variables
        run: |
          echo $HOME
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: main
          sparse-checkout: "cmd/cpi-count"
          sparse-checkout-cone-mode: false
      - name: Move cpi-count files to root
        run: |
          mv cmd/cpi-count/* .
          rm -rf cmd
          ls -al
      - name: Install `go`
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.9"
      - name: Print go version
        run: go version
      - name: Run cpi-count binary
        run: go build . && ./cpi-count
      - name: Run tests
        run: go test -count=1 ./...

  cleanup-runner:
    name: Stop EC2 runner
    needs: [setup-runner, ensure-perf-event-paranoid, run-tests]
    runs-on: ubuntu-latest
    if: always() # Run even if previous jobs fail
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Stop AWS Runner
        uses: ./.github/actions/aws-runner/cleanup
        with:
          runner-label: ${{ needs.setup-runner.outputs.runner-label }}
          ec2-instance-id: ${{ needs.setup-runner.outputs.ec2-instance-id }}
          github-token: ${{ secrets.REPO_ADMIN_TOKEN }}
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
